### ISSUE TITLE
updated to 1.6

### ISSUE THREAD

**Issue by waynelapierre** [bkamins/The-Julia-Express#10]
Will you update this document to Julia 1.6?

**Comment by bkamins** [comment]
Yes, when Julia 1.6 is out.

**Comment by bkamins** [comment]
Julia 1.5 did not introduce anything that required changes in 1.4.2 document

**Comment by waynelapierre** [comment]
Two small suggestions: 1. show some basic statistics functions in the Statistics and machine learning section. Maybe it is better to just call it Statistics. 2. use pure Julia plotting packages instead of PyPlot.

**Comment by bkamins** [comment]
Thank you for the suggestions. Which exactly package you consider "pure Julia plotting package"? And what benefits the user would get by using it? I use PyPlot.jl because most people already know matplotlib + PyPlot.jl is fast to load and fast to get a first plot.

**Comment by waynelapierre** [comment]
The assumption that most people already know matplotlib + PyPlot.jl may not be accurate. I use the GR backend. Many users only have experience with Matlab and R. 
The goal of Julia is to solve the two-language problem. It makes no sense to encourage people to use PyPlot.

**Comment by bkamins** [comment]
Sure, but GR is not written in Julia either. Julia only provides bindings to https://gr-framework.org/ just like PyPlot.jl to matplotlib. I am aware of benefits of GR.jl over PyPlot.jl, and the API for GR.jl has to be learned from scratch.

Anyway - maybe I will just switch to Plots.jl? I hesitated with this earlier, but in 1.6 "time to first plot" problem should be much less visible.

**Comment by waynelapierre** [comment]
sure, just use Plots.jl

**Comment by bkamins** [comment]
done
