### ISSUE TITLE
Some advices

### ISSUE THREAD

**Issue by johnnychen94** [bkamins/The-Julia-Express#2]
### p2

> 6) putting `;` after the expression will disable showing its value.

I think it's better to notice that `;` only works for REPL mode, and that there's no need to write `;` to deprecate the output if it's run by `julia script.jl`

### abstract type (p6)
you might forget things about `abstract type` and type inherit, e.g., `struct CustomNumber <: Number end`

### Function dispatch

I think it's more concise to put things about function dispatch alone, since it's quite important in understanding and writing Julia codes.

**Comment by bkamins** [comment]
Thank you for a careful reading!
I have updated the document while trying to keep it concise which is a challenge.
