### ISSUE TITLE
Sources are stale

### ISSUE THREAD

**Issue by jwakely** [bkamins/The-Julia-Express#3]
The `.ipynb` file in the Git Hub repo does not correspond to the latest PDF that the `README.md` links to.

I wanted to send a pull request for some spelling and grammar fixes, but the file is out of date.

**Comment by bkamins** [comment]
Thank you!

I have moved to TeX only version some time ago. I have moved out Jupyter Notebook for Julia 0.5 out of the repository to avoid confusion (it is still available for download).

I have added TeX sources in `/TeX` directory now (and also fixed some typos prompted by your issue - probably not all). Any comments would be much appreciated!

**Comment by jwakely** [comment]
Thanks! I'll take another look at the TeX.
