### ISSUE TITLE
Deprecated function name `squeeze' since version 0.7

### ISSUE THREAD

**Issue by Xiangsong-Guan** [bkamins/The-Julia-Express#5]
https://github.com/bkamins/The-Julia-Express/blob/be58602886d0237ece1acbc4f627ef8301e4934b/TeX/julia_express.tex#L318

According to [the 0.7 release notes](https://docs.julialang.org/en/v0.7.0/NEWS/) `dropdims` has replaced `squeeze`.

Some other information: https://github.com/JuliaLang/julia/pull/28303

**Comment by bkamins** [comment]
Thank you. I have fixed this.
