### ISSUE TITLE
Live HTML version of the book?

### ISSUE THREAD

**Issue by tseemann** [bkamins/The-Julia-Express#7]
It would be great if a HTML version of the book was online, say at `The-Julia-Express.github.io` using Github Pages. 

I'm not sure what the state of the art of Latex to HTML is, I last used `latex2html` in 2002.

This would make it easier for people with vision difficulties to read it in a flow like manner.

**Comment by bkamins** [comment]
I will try to check it out. However, for me to understand the issue better, can you please comment more what is the problem with PDF? You can have a "continuous reading" mode in PDF and then a viewer allows you to scroll the whole text (without "jumping" at page breaks).

**Comment by kartoffelkage** [comment]
If you're looking for HTML do you can reflow the page, try [Pandoc](https://pandoc.org/).

`` 
pandoc -i julia_express.tex -f latex -t html5 -s -o julia_express.html
``
No fancy styling, but that might even be a plus in this case.

**Comment by bkamins** [comment]
An excellent point. Thank you. I have just checked that the output looks OK. I am closing it and adding the instruction to the manual (@tseemann - if you have some more comments please reopen the issue).

**Comment by tseemann** [comment]
OK thank you. PDF reflow is terrible. I can control fonts and read much better with HTML.
